//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Teams')
export class TeamsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  teamName: string;

  @Column('text', { nullable: true })
  teamLogo: string;

  @Column('text', { nullable: true })
  captain: string;

  @Column('text', { nullable: true })
  playersBowlerOrBatsman: string;
}
