//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('WorldCricketMatches')
export class WorldCricketMatchesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  location: string;

  @Column('text', { nullable: true })
  teamsInvolved: string;

  @Column('date', { nullable: true })
  matchDate: Date;
}
