//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    WorldCricketMatches: [
      {
        location: 'location 1',
        teamsInvolved: 'teamsInvolved 1',
        matchDate: '2023-09-23T05:24:40.417Z',
        id: 8,
      },
      {
        location: 'location 2',
        teamsInvolved: 'teamsInvolved 2',
        matchDate: '2023-05-01T18:59:37.616Z',
        id: 57,
      },
      {
        location: 'location 3',
        teamsInvolved: 'teamsInvolved 3',
        matchDate: '2024-08-29T13:56:37.982Z',
        id: 2,
      },
      {
        location: 'location 4',
        teamsInvolved: 'teamsInvolved 4',
        matchDate: '2024-05-20T16:39:41.195Z',
        id: 98,
      },
      {
        location: 'location 5',
        teamsInvolved: 'teamsInvolved 5',
        matchDate: '2024-08-28T10:20:42.114Z',
        id: 51,
      },
    ],
    CountryMatches: [
      { allTeams: 'allTeams 1', id: 23 },
      { allTeams: 'allTeams 2', id: 42 },
      { allTeams: 'allTeams 3', id: 34 },
      { allTeams: 'allTeams 4', id: 76 },
      { allTeams: 'allTeams 5', id: 87 },
    ],
    Teams: [
      {
        teamName: 'teamName 1',
        teamLogo: 'teamLogo 1',
        captain: 'captain 1',
        playersBowlerOrBatsman: 'playersBowlerOrBatsman 1',
        id: 9,
      },
      {
        teamName: 'teamName 2',
        teamLogo: 'teamLogo 2',
        captain: 'captain 2',
        playersBowlerOrBatsman: 'playersBowlerOrBatsman 2',
        id: 78,
      },
      {
        teamName: 'teamName 3',
        teamLogo: 'teamLogo 3',
        captain: 'captain 3',
        playersBowlerOrBatsman: 'playersBowlerOrBatsman 3',
        id: 93,
      },
      {
        teamName: 'teamName 4',
        teamLogo: 'teamLogo 4',
        captain: 'captain 4',
        playersBowlerOrBatsman: 'playersBowlerOrBatsman 4',
        id: 11,
      },
      {
        teamName: 'teamName 5',
        teamLogo: 'teamLogo 5',
        captain: 'captain 5',
        playersBowlerOrBatsman: 'playersBowlerOrBatsman 5',
        id: 37,
      },
    ],
    User: [
      {
        mobileNumber: 'mobileNumber 1',
        password: 'password 1',
        preferredLanguage: 'preferredLanguage 1',
        id: 98,
      },
      {
        mobileNumber: 'mobileNumber 2',
        password: 'password 2',
        preferredLanguage: 'preferredLanguage 2',
        id: 22,
      },
      {
        mobileNumber: 'mobileNumber 3',
        password: 'password 3',
        preferredLanguage: 'preferredLanguage 3',
        id: 100,
      },
      {
        mobileNumber: 'mobileNumber 4',
        password: 'password 4',
        preferredLanguage: 'preferredLanguage 4',
        id: 84,
      },
      {
        mobileNumber: 'mobileNumber 5',
        password: 'password 5',
        preferredLanguage: 'preferredLanguage 5',
        id: 51,
      },
    ],
  },
};
export default data;
